---
- hosts: all
  become: true
  tasks:
  - name: Install Docker
    apt: name=docker.io state=present
  - name: Start Docker Service
    command: sudo systemctl start docker
  - name: Deploy your application and runs as a container
    command: docker run -itd -p 8084:8081 belosheabhijeet/insureme-app:7.0
